config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :tracks
  resources :users
  root to: "statics#home"
  get "tags/:tag", to: "tracks#index", as: :tag
  get "/my_tracks", to: "tracks#index", my_tracks: true
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      # defines abilities
      if user.admin?
        can :manage, :all  
      else
        can :create, Comment
        can :read, :all
        can :edit, Comment, user_id: user.id
        can :destroy, Comment, user_id: user.id
        
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/track.rb
class Track < ActiveRecord::Base
  acts_as_taggable
  #has_many :tags
  belongs_to :user
  has_many :comments

  validates :title, presence: true, uniqueness: true, length: { minimum: 2 }
  validates :track_image, presence: true

  mount_uploader :track_image, TrackImageUploader
  mount_uploader :audio_track, AudioTrackUploader


end

app/models/user.rb
class User < ActiveRecord::Base  
  has_many :tracks
  has_many :comments, through: :tracks

  mount_uploader :photo, ProfilePicUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true, length: { minimum: 2 }
  validates :email, presence: true, uniqueness: true

  def admin?
    self.role == "Admin"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # def after_sign_in_path_for(resource)
  #   secret_path
  # end

  before_filter :configure_devise_params, if: :devise_controller?

  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :username, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  
  before_filter :set_commentable
  before_filter :set_comment, only: [:destroy]

  def create
    @comment = @commentable.comments.build(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @commentable }
      else
        format.html { render :action => 'new' }
      end
    end
  end

  def destroy
    @comment.destroy
    redirect_to @commentable
  end

  private 
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_commentable
      @commentable = params[:commentable_type].camelize.constantize.find(params[:commentable_id])
    end

    def comment_params
      params.require(:comment).permit(:comment)
    end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    # @tracks = current_user ? current_user.tracks : []  
    @tracks = if params[:my_tracks]
       current_user.tracks
     elsif params[:tag]
         Track.tagged_with params[:tag]
    else 
      Track.all
    end
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = current_user.tracks.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:title, :user_id, :tag_id, :track_image, :remote_track_image_url, :audio_track, :tag_list)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  #to check if a given user can edit an item #defines what the users are allowed to do

  # GET /users/1/edit 
  # def edit  
  #   authorize! :edit, @item
  # end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :photo, :remote_photo_url, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li><%= comment.comment %></li>
<li><%= comment.user.try(:username) %></li>
<% if can? :destroy, comment %>
  <li><%= link_to 'Remove', comment_path(comment, commentable_type: commentable.class, commentable_id: commentable.id), method: :delete, data: { confirm: 'Are you sure?' } %></li>

<% end %>

app/views/comments/_form.html.erb
<%= form_for(:comment, url: comments_path(commentable_type: commentable.class.to_s.underscore, commentable_id: commentable.id)) do |f| %>

  <%= f.label :comment %>
  <%= f.text_field :comment %>

  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href='http://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="http://i.icomoon.io/public/temp/a6d01971a8/UntitledProject/style.css">

  <title><%= content_for?(:title) ? yield(:title) : "Mixtape" %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<header>
<div class="off-canvas-wrap" data-offcanvas>
  <div class="inner-wrap">
    <nav class="tab-bar">
      <section class="left-small">
        <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
      </section>

      <section class="middle tab-bar-section">
        <h1 class="title"><span class="icon-cassette"></span>Mixtape</h1>
      </section>

      <section class="right-small">
        <a class="right-off-canvas-toggle menu-icon" href="#"><span></span></a>
      </section>
    </nav>

    <aside class="left-off-canvas-menu">
      <ul class="off-canvas-list">
        <li><label>Menu</label></li>
        <li><%= link_to "Upload Track", new_track_path %></li>
        <li><%= link_to "Tracks", tracks_path %></li>

      </ul>
    </aside>

    <aside class="right-off-canvas-menu">
      <ul class="off-canvas-list">
        <li><label>My Options</label></li>
        <% if current_user %>
          <li><%= link_to "My Tracks", my_tracks_path%></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </aside>

    <section class="main-section">
      <!-- content goes here -->
        <main class="row">
          <%= yield %>
        </main>
      </section>

    <a class="exit-off-canvas"></a>

    </div>
  </div>
  </header>

</body>
</html>

app/views/statics/home.html.erb
<h2>Upload your tracks for feedback</h2>

<div>
  <a href="http://imgur.com/NbQp4j6"><img src="http://i.imgur.com/NbQp4j6.jpg" title="source: imgur.com" /></a>
</div>

<h3>Create your own Mixtapes</h3>

app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
<% if @track.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

  <ul>
    <% @track.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :track_image %><br>
  <%= f.file_field :track_image %>
</div>
<div class="field">
  <%= f.label :remote_track_image_url %><br>
  <%= f.text_field :remote_track_image_url %>
</div>
<div class="field">
  <%= f.label :audio_track %><br>
  <%= f.file_field :audio_track %>
</div>
<div class="field">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br>
  <%= f.text_field :tag_list %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/tracks/_track.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="small-12 columns play-track"> 
    <h1><%= link_to track.title, track %></h1>
    <p><%= track.user.try(:username) %></p>
    <div class="play-square" 
    style="background-image: url(<%= track.track_image.detail.url %>); background-repeat: no-repeat">

  </div>
</div>
</div>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %> |

app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Listing Tracks
  <%= " tagged with #{params[:tag]}" if params[:tag] %>
</h1>
<div id="tag_cloud">
  <% tag_cloud Track.tag_counts, %w[s m l] do |tag, css_class| %>
  <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  
  <% end %>
</div>

<%= render @tracks %>

<br>

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="small-12 columns play-track"> 
    <h1>Tracks</h1>
    <div class="play-square" 
    style="background-image: url(<%= @track.track_image.detail.url %>); background-repeat: no-repeat" data-url="<%= @track.audio_track.url %>">
  </div>
  <div class="small-12 columns">
    <audio controls src="<%= @track.audio_track.url %>"></audio>
    <%= @track.tag_id %>
  </div>
</div>
<div class="track-info small-12 columns">
  <p class="small-6">Track title: <%= @track.title %></p>
  <p class="small-6">Artist name: <%= @track.user.try(:username) %></p>
  <p> Tags: <%= @track.tag_list %></p>
</div>

<ul>
  <%= render partial: 'comments/comment', collection: @track.comments, locals: { commentable: @track } %>
</ul>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %> |
<%= link_to 'Delete', @track, method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %>

<%= render partial: 'comments/form', locals: { commentable: @track } %>

</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :username %><br>
  <%= f.text_field :username %>
</div>
<div class="field">
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :photo %><br>
  <%= f.file_field :photo %>
</div>
<div class="field">
  <%= f.label :remote_photo_url %><br>
  <%= f.text_field :remote_photo_url %>
</div>
<div class="field">
  <%= f.label :role %><br>
  <%= f.text_field :role %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Photo</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= image_tag user.photo.url %></td>
      <td><%= user.role %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag@user.photo.thumb.url %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>